apiVersion: v1
kind: Service
metadata:
  name: viaserver
  labels:
    run: viaserver
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30100
    protocol: TCP
    name: viaserver-http
  selector:
    service: viaserver
