apiVersion: v1
kind: Service
metadata:
  name: pybossa
  labels:
    run: pybossa
spec:
  type: NodePort
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30090
    protocol: TCP
    name: pybossa-http
  selector:
    service: pybossa

