apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
    protocol: TCP
    name: db
  selector:
    service: postgres
