apiVersion: v1
kind: Service
metadata:
  name: hserver
  labels:
    run: hserver
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: hserver-http
  selector:
    service: hserver
