apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - image: postgres:9.6-alpine
          imagePullPolicy: Always
          name: postgres
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 5432
              name: postgres-tcp
      # [START volumes]
      # [END volumes]
